# frozen_string_literal: true

# Generated by Sterling SDK Generator — test suite
# Orchestrator Control Plane API v0.1.0

require "minitest/autorun"
require "json"

require_relative "../lib/vers_sdk"

class TestVersSdkClient < Minitest::Test
  def setup
    @client = VersSdk::VersSdkClient.new(
      base_url: "http://localhost:9999",
      api_key: "test-key",
      max_retries: 0
    )
  end

  def test_vm_status_method_exists
    assert_respond_to @client, :vm_status
  end

  def test_resize_vm_disk_method_exists
    assert_respond_to @client, :resize_vm_disk
  end

  def test_exec_vm_stream_attach_method_exists
    assert_respond_to @client, :exec_vm_stream_attach
  end

  def test_list_vms_method_exists
    assert_respond_to @client, :list_vms
  end

  def test_create_new_root_vm_method_exists
    assert_respond_to @client, :create_new_root_vm
  end

  def test_vm_logs_method_exists
    assert_respond_to @client, :vm_logs
  end

  def test_branch_by_ref_method_exists
    assert_respond_to @client, :branch_by_ref
  end

  def test_label_vm_method_exists
    assert_respond_to @client, :label_vm
  end

  def test_list_public_commits_method_exists
    assert_respond_to @client, :list_public_commits
  end

  def test_get_image_status_method_exists
    assert_respond_to @client, :get_image_status
  end

  def test_list_public_repo_tags_method_exists
    assert_respond_to @client, :list_public_repo_tags
  end

  def test_version_handler_method_exists
    assert_respond_to @client, :version_handler
  end

  def test_branch_by_tag_method_exists
    assert_respond_to @client, :branch_by_tag
  end

  def test_get_repo_tag_method_exists
    assert_respond_to @client, :get_repo_tag
  end

  def test_delete_repo_tag_method_exists
    assert_respond_to @client, :delete_repo_tag
  end

  def test_update_repo_tag_method_exists
    assert_respond_to @client, :update_repo_tag
  end

  def test_branch_vm_method_exists
    assert_respond_to @client, :branch_vm
  end

  def test_get_repository_method_exists
    assert_respond_to @client, :get_repository
  end

  def test_delete_repository_method_exists
    assert_respond_to @client, :delete_repository
  end

  def test_list_parent_commits_method_exists
    assert_respond_to @client, :list_parent_commits
  end

  def test_validate_key_method_exists
    assert_respond_to @client, :validate_key
  end

  def test_fork_repository_method_exists
    assert_respond_to @client, :fork_repository
  end

  def test_list_repositories_method_exists
    assert_respond_to @client, :list_repositories
  end

  def test_create_repository_method_exists
    assert_respond_to @client, :create_repository
  end

  def test_update_vm_state_method_exists
    assert_respond_to @client, :update_vm_state
  end

  def test_create_image_method_exists
    assert_respond_to @client, :create_image
  end

  def test_restore_from_commit_method_exists
    assert_respond_to @client, :restore_from_commit
  end

  def test_get_domain_method_exists
    assert_respond_to @client, :get_domain
  end

  def test_delete_domain_method_exists
    assert_respond_to @client, :delete_domain
  end

  def test_list_tags_method_exists
    assert_respond_to @client, :list_tags
  end

  def test_create_tag_method_exists
    assert_respond_to @client, :create_tag
  end

  def test_list_public_repositories_method_exists
    assert_respond_to @client, :list_public_repositories
  end

  def test_get_public_repo_tag_method_exists
    assert_respond_to @client, :get_public_repo_tag
  end

  def test_list_vms_method_exists
    assert_respond_to @client, :list_vms
  end

  def test_get_vm_metadata_method_exists
    assert_respond_to @client, :get_vm_metadata
  end

  def test_list_env_vars_method_exists
    assert_respond_to @client, :list_env_vars
  end

  def test_set_env_vars_method_exists
    assert_respond_to @client, :set_env_vars
  end

  def test_delete_vm_method_exists
    assert_respond_to @client, :delete_vm
  end

  def test_list_commits_method_exists
    assert_respond_to @client, :list_commits
  end

  def test_get_tag_method_exists
    assert_respond_to @client, :get_tag
  end

  def test_delete_tag_method_exists
    assert_respond_to @client, :delete_tag
  end

  def test_update_tag_method_exists
    assert_respond_to @client, :update_tag
  end

  def test_branch_by_vm_method_exists
    assert_respond_to @client, :branch_by_vm
  end

  def test_delete_env_var_method_exists
    assert_respond_to @client, :delete_env_var
  end

  def test_delete_image_method_exists
    assert_respond_to @client, :delete_image
  end

  def test_commit_vm_method_exists
    assert_respond_to @client, :commit_vm
  end

  def test_delete_commit_method_exists
    assert_respond_to @client, :delete_commit
  end

  def test_update_commit_method_exists
    assert_respond_to @client, :update_commit
  end

  def test_list_repo_tags_method_exists
    assert_respond_to @client, :list_repo_tags
  end

  def test_create_repo_tag_method_exists
    assert_respond_to @client, :create_repo_tag
  end

  def test_deploy_handler_method_exists
    assert_respond_to @client, :deploy_handler
  end

  def test_exec_vm_method_exists
    assert_respond_to @client, :exec_vm
  end

  def test_set_repository_visibility_method_exists
    assert_respond_to @client, :set_repository_visibility
  end

  def test_exec_vm_stream_method_exists
    assert_respond_to @client, :exec_vm_stream
  end

  def test_list_domains_method_exists
    assert_respond_to @client, :list_domains
  end

  def test_create_domain_method_exists
    assert_respond_to @client, :create_domain
  end

  def test_ssh_key_method_exists
    assert_respond_to @client, :ssh_key
  end

  def test_list_images_method_exists
    assert_respond_to @client, :list_images
  end

  def test_read_file_vm_method_exists
    assert_respond_to @client, :read_file_vm
  end

  def test_write_file_vm_method_exists
    assert_respond_to @client, :write_file_vm
  end

  def test_upload_image_method_exists
    assert_respond_to @client, :upload_image
  end

  def test_get_public_repository_method_exists
    assert_respond_to @client, :get_public_repository
  end

  def test_branch_by_commit_method_exists
    assert_respond_to @client, :branch_by_commit
  end


  # ── Error class tests ─────────────────────────────────────────────────

  def test_api_error_generate_400
    err = VersSdk::APIError.generate(status: 400, body: { "message" => "bad" }, headers: {})
    assert_instance_of VersSdk::BadRequestError, err
    assert_equal 400, err.status
  end

  def test_api_error_generate_401
    err = VersSdk::APIError.generate(status: 401, body: { "message" => "unauthorized" }, headers: {})
    assert_instance_of VersSdk::AuthenticationError, err
  end

  def test_api_error_generate_403
    err = VersSdk::APIError.generate(status: 403, body: nil, headers: {})
    assert_instance_of VersSdk::PermissionDeniedError, err
  end

  def test_api_error_generate_404
    err = VersSdk::APIError.generate(status: 404, body: { "message" => "not found" }, headers: {})
    assert_instance_of VersSdk::NotFoundError, err
    assert_equal 404, err.status
  end

  def test_api_error_generate_409
    err = VersSdk::APIError.generate(status: 409, body: nil, headers: {})
    assert_instance_of VersSdk::ConflictError, err
  end

  def test_api_error_generate_422
    err = VersSdk::APIError.generate(status: 422, body: nil, headers: {})
    assert_instance_of VersSdk::UnprocessableEntityError, err
  end

  def test_api_error_generate_429
    err = VersSdk::APIError.generate(status: 429, body: nil, headers: {})
    assert_instance_of VersSdk::RateLimitError, err
  end

  def test_api_error_generate_500
    err = VersSdk::APIError.generate(status: 500, body: { "message" => "server error" }, headers: {})
    assert_instance_of VersSdk::InternalServerError, err
  end

  def test_api_connection_error
    err = VersSdk::APIConnectionError.new
    assert_instance_of VersSdk::APIConnectionError, err
    assert_match(/Connection error/, err.message)
  end

  def test_api_connection_timeout_error
    err = VersSdk::APIConnectionTimeoutError.new
    assert_instance_of VersSdk::APIConnectionTimeoutError, err
    assert_match(/timed out/, err.message)
  end

  def test_client_defaults
    client = VersSdk::VersSdkClient.new
    assert_equal "https://api.vers.sh", client.base_url
    assert_equal 2, client.max_retries
    assert_equal 30, client.timeout
  end
end
