# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "vers-sdk"
  spec.version = "0.1.8"
  spec.summary = "SDK for Orchestrator Control Plane API"
  spec.description = "Ruby client library for the Orchestrator Control Plane API API. Generated by Sterling."
  spec.authors = ["Sterling SDK Generator"]
  spec.license = "MIT"
  spec.required_ruby_version = ">= 3.0"

  spec.files = Dir["lib/**/*.rb"]
  spec.require_paths = ["lib"]

  spec.metadata = {
    "source_code_uri" => "https://github.com/hdresearch/ruby-sdk",
    "homepage_uri" => "https://github.com/hdresearch/ruby-sdk"
  }
end
