# frozen_string_literal: true

# Generated by Sterling SDK Generator
# Orchestrator Control Plane API v0.1.0

require "net/http"
require "uri"
require "json"
require "securerandom"
require "logger"
require "time"

require_relative "errors"
require_relative "models"

module VersSdk
  # Per-request options that override client defaults.
  class RequestOptions
    attr_accessor :headers, :timeout

    def initialize(headers: nil, timeout: nil)
      @headers = headers
      @timeout = timeout
    end
  end

  LOG_LEVEL_MAP = {
    "debug" => Logger::DEBUG,
    "info" => Logger::INFO,
    "warn" => Logger::WARN,
    "error" => Logger::ERROR,
    "off" => Logger::UNKNOWN
  }.freeze

  RETRYABLE_STATUS_CODES = [408, 409, 429].freeze

  # HTTP client for Orchestrator Control Plane API.
  class VersSdkClient
    attr_reader :base_url, :max_retries, :timeout

    # @param base_url [String, nil] API base URL (default: VERS_BASE_URL env or https://api.vers.sh)
    # @param api_key [String, nil] Bearer token (default: VERS_API_KEY env)
    # @param max_retries [Integer] Maximum number of retries (default: 2)
    # @param timeout [Numeric] Request timeout in seconds (default: 30)
    def initialize(base_url: nil, api_key: nil, max_retries: 2, timeout: 30)
      @base_url = base_url || ENV.fetch("VERS_BASE_URL", "https://api.vers.sh")
      @api_key = api_key || ENV["VERS_API_KEY"]
      @max_retries = max_retries
      @timeout = timeout
      @logger = self.class.build_logger
      @default_headers = {
        "Content-Type" => "application/json",
        "Accept" => "application/json",
        "User-Agent" => "vers-sdk/0.1.8 ruby/#{RUBY_VERSION} #{RUBY_PLATFORM}"
      }
      @default_headers["Authorization"] = "Bearer #{@api_key}" if @api_key
    end

    def self.build_logger
      logger = Logger.new($stdout)
      env_level = ENV.fetch("VERS_LOG", "warn").downcase
      logger.level = LOG_LEVEL_MAP.fetch(env_level, Logger::WARN)
      logger.formatter = proc { |severity, datetime, _progname, msg|
        "#{datetime} [vers_sdk #{severity}] #{msg}\n"
      }
      logger
    end

    # 
    def vm_status(vm_id, options: nil)
      path = sprintf("/api/v1/vm/%s/status", vm_id)
      request("GET", path, options: options)
    end

    # 
    def resize_vm_disk(vm_id, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/disk", vm_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("PATCH", path, options: options, body: body, query: query)
    end

    # 
    def exec_vm_stream_attach(vm_id, body: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/exec/stream/attach", vm_id)
      request("POST", path, options: options, body: body)
    end

    # 
    def list_vms(options: nil)
      path = "/api/v1/vms"
      request("GET", path, options: options)
    end

    # 
    def create_new_root_vm(body: nil, params: nil, options: nil)
      path = "/api/v1/vm/new_root"
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("POST", path, options: options, body: body, query: query)
    end

    # 
    def vm_logs(vm_id, params: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/logs", vm_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("GET", path, options: options, query: query)
    end

    # 
    def branch_by_ref(repo_name, tag_name, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/branch/by_ref/%s/%s", repo_name, tag_name)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("POST", path, options: options, body: body, query: query)
    end

    # 
    def label_vm(vm_id, body: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/label", vm_id)
      request("PATCH", path, options: options, body: body)
    end

    # 
    def list_public_commits(options: nil)
      path = "/api/v1/commits/public"
      request("GET", path, options: options)
    end

    # 
    def get_image_status(image_name, options: nil)
      path = sprintf("/api/v1/images/%s/status", image_name)
      request("GET", path, options: options)
    end

    # 
    def list_public_repo_tags(org_name, repo_name, options: nil)
      path = sprintf("/api/v1/public/repositories/%s/%s/tags", org_name, repo_name)
      request("GET", path, options: options)
    end

    # 
    def version_handler(options: nil)
      path = "/api/v1/system/version"
      request("GET", path, options: options)
    end

    # 
    def branch_by_tag(tag_name, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/branch/by_tag/%s", tag_name)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("POST", path, options: options, body: body, query: query)
    end

    # 
    def get_repo_tag(repo_name, tag_name, options: nil)
      path = sprintf("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
      request("GET", path, options: options)
    end

    # 
    def delete_repo_tag(repo_name, tag_name, options: nil)
      path = sprintf("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
      request("DELETE", path, options: options)
    end

    # 
    def update_repo_tag(repo_name, tag_name, body: nil, options: nil)
      path = sprintf("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
      request("PATCH", path, options: options, body: body)
    end

    # 
    def branch_vm(vm_or_commit_id, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/branch", vm_or_commit_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("POST", path, options: options, body: body, query: query)
    end

    # 
    def get_repository(repo_name, options: nil)
      path = sprintf("/api/v1/repositories/%s", repo_name)
      request("GET", path, options: options)
    end

    # 
    def delete_repository(repo_name, options: nil)
      path = sprintf("/api/v1/repositories/%s", repo_name)
      request("DELETE", path, options: options)
    end

    # 
    def list_parent_commits(commit_id, options: nil)
      path = sprintf("/api/v1/vm/commits/%s/parents", commit_id)
      request("GET", path, options: options)
    end

    # 
    def validate_key(body: nil, options: nil)
      path = "/api/v1/keys/validate"
      request("POST", path, options: options, body: body)
    end

    # 
    def fork_repository(body: nil, options: nil)
      path = "/api/v1/repositories/fork"
      request("POST", path, options: options, body: body)
    end

    # 
    def list_repositories(options: nil)
      path = "/api/v1/repositories"
      request("GET", path, options: options)
    end

    # 
    def create_repository(body: nil, options: nil)
      path = "/api/v1/repositories"
      request("POST", path, options: options, body: body)
    end

    # 
    def update_vm_state(vm_id, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/state", vm_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("PATCH", path, options: options, body: body, query: query)
    end

    # 
    def create_image(body: nil, options: nil)
      path = "/api/v1/images/create"
      request("POST", path, options: options, body: body)
    end

    # 
    def restore_from_commit(body: nil, options: nil)
      path = "/api/v1/vm/from_commit"
      request("POST", path, options: options, body: body)
    end

    # 
    def get_domain(domain_id, options: nil)
      path = sprintf("/api/v1/domains/%s", domain_id)
      request("GET", path, options: options)
    end

    # 
    def delete_domain(domain_id, options: nil)
      path = sprintf("/api/v1/domains/%s", domain_id)
      request("DELETE", path, options: options)
    end

    # 
    def list_tags(options: nil)
      path = "/api/v1/commit_tags"
      request("GET", path, options: options)
    end

    # 
    def create_tag(body: nil, options: nil)
      path = "/api/v1/commit_tags"
      request("POST", path, options: options, body: body)
    end

    # 
    def list_public_repositories(options: nil)
      path = "/api/v1/public/repositories"
      request("GET", path, options: options)
    end

    # 
    def get_public_repo_tag(org_name, repo_name, tag_name, options: nil)
      path = sprintf("/api/v1/public/repositories/%s/%s/tags/%s", org_name, repo_name, tag_name)
      request("GET", path, options: options)
    end

    # 
    def get_vm_metadata(vm_id, options: nil)
      path = sprintf("/api/v1/vm/%s/metadata", vm_id)
      request("GET", path, options: options)
    end

    # 
    def list_env_vars(options: nil)
      path = "/api/v1/env_vars"
      request("GET", path, options: options)
    end

    # 
    def set_env_vars(body: nil, options: nil)
      path = "/api/v1/env_vars"
      request("PUT", path, options: options, body: body)
    end

    # 
    def delete_vm(vm_id, params: nil, options: nil)
      path = sprintf("/api/v1/vm/%s", vm_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("DELETE", path, options: options, query: query)
    end

    # 
    def list_commits(options: nil)
      path = "/api/v1/commits"
      request("GET", path, options: options)
    end

    # 
    def get_tag(tag_name, options: nil)
      path = sprintf("/api/v1/commit_tags/%s", tag_name)
      request("GET", path, options: options)
    end

    # 
    def delete_tag(tag_name, options: nil)
      path = sprintf("/api/v1/commit_tags/%s", tag_name)
      request("DELETE", path, options: options)
    end

    # 
    def update_tag(tag_name, body: nil, options: nil)
      path = sprintf("/api/v1/commit_tags/%s", tag_name)
      request("PATCH", path, options: options, body: body)
    end

    # 
    def branch_by_vm(vm_id, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/branch/by_vm/%s", vm_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("POST", path, options: options, body: body, query: query)
    end

    # 
    def delete_env_var(key, options: nil)
      path = sprintf("/api/v1/env_vars/%s", key)
      request("DELETE", path, options: options)
    end

    # 
    def delete_image(base_image_id, options: nil)
      path = sprintf("/api/v1/images/images/%s", base_image_id)
      request("DELETE", path, options: options)
    end

    # 
    def commit_vm(vm_id, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/commit", vm_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("POST", path, options: options, body: body, query: query)
    end

    # 
    def delete_commit(commit_id, options: nil)
      path = sprintf("/api/v1/commits/%s", commit_id)
      request("DELETE", path, options: options)
    end

    # 
    def update_commit(commit_id, body: nil, options: nil)
      path = sprintf("/api/v1/commits/%s", commit_id)
      request("PATCH", path, options: options, body: body)
    end

    # 
    def list_repo_tags(repo_name, options: nil)
      path = sprintf("/api/v1/repositories/%s/tags", repo_name)
      request("GET", path, options: options)
    end

    # 
    def create_repo_tag(repo_name, body: nil, options: nil)
      path = sprintf("/api/v1/repositories/%s/tags", repo_name)
      request("POST", path, options: options, body: body)
    end

    # Deploy a GitHub repository to a new Vers project.
    def deploy_handler(body: nil, options: nil)
      path = "/api/v1/deploy"
      request("POST", path, options: options, body: body)
    end

    # 
    def exec_vm(vm_id, body: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/exec", vm_id)
      request("POST", path, options: options, body: body)
    end

    # 
    def set_repository_visibility(repo_name, body: nil, options: nil)
      path = sprintf("/api/v1/repositories/%s/visibility", repo_name)
      request("PATCH", path, options: options, body: body)
    end

    # 
    def exec_vm_stream(vm_id, body: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/exec/stream", vm_id)
      request("POST", path, options: options, body: body)
    end

    # 
    def list_domains(params: nil, options: nil)
      path = "/api/v1/domains"
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("GET", path, options: options, query: query)
    end

    # 
    def create_domain(body: nil, options: nil)
      path = "/api/v1/domains"
      request("POST", path, options: options, body: body)
    end

    # 
    def ssh_key(vm_id, options: nil)
      path = sprintf("/api/v1/vm/%s/ssh_key", vm_id)
      request("GET", path, options: options)
    end

    # 
    def list_images(options: nil)
      path = "/api/v1/images"
      request("GET", path, options: options)
    end

    # 
    def read_file_vm(vm_id, params: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/files", vm_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("GET", path, options: options, query: query)
    end

    # 
    def write_file_vm(vm_id, body: nil, options: nil)
      path = sprintf("/api/v1/vm/%s/files", vm_id)
      request("PUT", path, options: options, body: body)
    end

    # 
    def upload_image(body: nil, options: nil)
      path = "/api/v1/images/upload"
      request("POST", path, options: options, body: body)
    end

    # 
    def get_public_repository(org_name, repo_name, options: nil)
      path = sprintf("/api/v1/public/repositories/%s/%s", org_name, repo_name)
      request("GET", path, options: options)
    end

    # 
    def branch_by_commit(commit_id, body: nil, params: nil, options: nil)
      path = sprintf("/api/v1/vm/branch/by_commit/%s", commit_id)
      query = {}
      if params
        h = params.is_a?(Hash) ? params : params.to_h
        h.each { |k, v| query[k.to_s] = v.to_s unless v.nil? }
      end
      request("POST", path, options: options, body: body, query: query)
    end


    private

    def request(method, path, options: nil, body: nil, query: nil)
      uri = build_uri(path, query)
      @logger.debug("request: #{method} #{uri}")

      last_exc = nil
      retry_after_used = false

      (@max_retries + 1).times do |attempt|
        if attempt > 0 && !retry_after_used
          delay = retry_delay(attempt - 1)
          @logger.info("retry attempt #{attempt}/#{@max_retries} for #{method} #{path}")
          sleep(delay)
        end
        retry_after_used = false

        begin
          response = execute_request(method, uri, body: body, options: options)
          status = response.code.to_i
          @logger.debug("response: #{status} for #{method} #{path}")

          if retryable_status?(status) && attempt < @max_retries
            ra_delay = parse_retry_after(response["Retry-After"])
            if ra_delay
              retry_after_used = true
              @logger.info("retry attempt #{attempt + 1}/#{@max_retries} for #{method} #{path} (retry-after: #{ra_delay}s)")
              sleep(ra_delay)
            end
            last_exc = StandardError.new("HTTP #{status}")
            next
          end

          check_response(response)
          return JSON.parse(response.body) rescue response.body
        rescue APIError
          raise
        rescue Errno::ECONNREFUSED, Errno::ECONNRESET, Errno::ETIMEDOUT,
               Net::OpenTimeout, Net::ReadTimeout, SocketError => e
          @logger.error("connection error: #{method} #{path} - #{e.message}")
          raise APIConnectionError.new(message: e.message, cause: e) if attempt == @max_retries

          last_exc = e
        end
      end

      raise last_exc if last_exc
    end

    def build_uri(path, query)
      uri = URI.join(@base_url, path)
      if query && !query.empty?
        uri.query = URI.encode_www_form(query)
      end
      uri
    end

    def execute_request(method, uri, body: nil, options: nil)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = (uri.scheme == "https")
      effective_timeout = (options&.timeout || @timeout)
      http.open_timeout = effective_timeout
      http.read_timeout = effective_timeout

      req = build_http_request(method, uri, body)

      # Merge default headers
      @default_headers.each { |k, v| req[k] = v }

      # Idempotency key for mutating methods
      if %w[POST PUT PATCH DELETE].include?(method)
        req["X-Idempotency-Key"] = SecureRandom.uuid
      end

      # Per-request header overrides
      if options&.headers
        options.headers.each do |k, v|
          if v.nil?
            req.delete(k)
          else
            req[k] = v
          end
        end
      end

      http.request(req)
    end

    def build_http_request(method, uri, body)
      request_path = uri.request_uri
      case method
      when "GET"
        Net::HTTP::Get.new(request_path)
      when "POST"
        req = Net::HTTP::Post.new(request_path)
        req.body = body.to_json if body
        req
      when "PUT"
        req = Net::HTTP::Put.new(request_path)
        req.body = body.to_json if body
        req
      when "PATCH"
        req = Net::HTTP::Patch.new(request_path)
        req.body = body.to_json if body
        req
      when "DELETE"
        Net::HTTP::Delete.new(request_path)
      else
        Net::HTTP::Get.new(request_path)
      end
    end

    def check_response(response)
      status = response.code.to_i
      return if status >= 200 && status < 300

      body = nil
      message = nil
      ct = response["content-type"] || ""
      if ct.include?("application/json")
        begin
          body = JSON.parse(response.body)
        rescue StandardError
          message = response.body
        end
      else
        message = response.body
      end

      headers = {}
      response.each_header { |k, v| headers[k] = v }

      raise APIError.generate(status: status, body: body, message: message, headers: headers)
    end

    def retryable_status?(status)
      status >= 500 || RETRYABLE_STATUS_CODES.include?(status)
    end

    def retry_delay(attempt)
      base = 0.5 * (2**attempt)
      jitter = rand * base * 0.25
      base + jitter
    end

    def parse_retry_after(header_value)
      return nil if header_value.nil?

      # Try numeric
      delay = Float(header_value)
      return [[delay, 0.0].max, 60.0].min
    rescue ArgumentError, TypeError
      # Try HTTP date
      begin
        retry_time = Time.httpdate(header_value)
        delay = retry_time - Time.now
        [[delay, 0.0].max, 60.0].min
      rescue ArgumentError
        nil
      end
    end
  end
end
