# frozen_string_literal: true

# Generated by Sterling SDK Generator
# Orchestrator Control Plane API v0.1.0

require "json"

module VersSdk
  # Response body for GET /env_vars and PUT /env_vars.
  class EnvVarsResponse
    attr_accessor :env_vars_response, 

    def initialize(attrs = {})
      @env_vars_response = attrs["vars"] || attrs[:env_vars_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "vars" => @env_vars_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for POST /api/v1/repositories
  class CreateRepositoryResponse
    attr_accessor :create_repository_response, :create_repository_response, 

    def initialize(attrs = {})
      @create_repository_response = attrs["name"] || attrs[:create_repository_response]
      @create_repository_response = attrs["repo_id"] || attrs[:create_repository_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "name" => @create_repository_response,
        "repo_id" => @create_repository_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Public repository information (includes owner org name for namespacing)
  class PublicRepositoryInfo
    attr_accessor :public_repository_info, :public_repository_info, :public_repository_info, :public_repository_info, :public_repository_info, :public_repository_info, 

    def initialize(attrs = {})
      @public_repository_info = attrs["created_at"] || attrs[:public_repository_info]
      @public_repository_info = attrs["description"] || attrs[:public_repository_info]
      @public_repository_info = attrs["full_name"] || attrs[:public_repository_info]
      @public_repository_info = attrs["name"] || attrs[:public_repository_info]
      @public_repository_info = attrs["org_name"] || attrs[:public_repository_info]
      @public_repository_info = attrs["repo_id"] || attrs[:public_repository_info]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "created_at" => @public_repository_info,
        "description" => @public_repository_info,
        "full_name" => @public_repository_info,
        "name" => @public_repository_info,
        "org_name" => @public_repository_info,
        "repo_id" => @public_repository_info,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for GET /api/v1/commit_tags
  class ListTagsResponse
    attr_accessor :list_tags_response, 

    def initialize(attrs = {})
      @list_tags_response = attrs["tags"] || attrs[:list_tags_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "tags" => @list_tags_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for creating a tag within a repository: POST /api/v1/repositories/{repo_name}/tags
  class CreateRepoTagRequest
    attr_accessor :create_repo_tag_request, :create_repo_tag_request, :create_repo_tag_request, 

    def initialize(attrs = {})
      @create_repo_tag_request = attrs["commit_id"] || attrs[:create_repo_tag_request]
      @create_repo_tag_request = attrs["description"] || attrs[:create_repo_tag_request]
      @create_repo_tag_request = attrs["tag_name"] || attrs[:create_repo_tag_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @create_repo_tag_request,
        "description" => @create_repo_tag_request,
        "tag_name" => @create_repo_tag_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response struct for GET api/v1/system/version
  class OrchestratorVersion
    attr_accessor :orchestrator_version, :orchestrator_version, :orchestrator_version, 

    def initialize(attrs = {})
      @orchestrator_version = attrs["executable_name"] || attrs[:orchestrator_version]
      @orchestrator_version = attrs["git_hash"] || attrs[:orchestrator_version]
      @orchestrator_version = attrs["workspace_version"] || attrs[:orchestrator_version]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "executable_name" => @orchestrator_version,
        "git_hash" => @orchestrator_version,
        "workspace_version" => @orchestrator_version,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class ListCommitsResponse
    attr_accessor :list_commits_response, :list_commits_response, :list_commits_response, :list_commits_response, 

    def initialize(attrs = {})
      @list_commits_response = attrs["commits"] || attrs[:list_commits_response]
      @list_commits_response = attrs["limit"] || attrs[:list_commits_response]
      @list_commits_response = attrs["offset"] || attrs[:list_commits_response]
      @list_commits_response = attrs["total"] || attrs[:list_commits_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commits" => @list_commits_response,
        "limit" => @list_commits_response,
        "offset" => @list_commits_response,
        "total" => @list_commits_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for `POST /api/v1/deploy`.
  class DeployResponse
    attr_accessor :deploy_response, :deploy_response, :deploy_response, 

    def initialize(attrs = {})
      @deploy_response = attrs["project_id"] || attrs[:deploy_response]
      @deploy_response = attrs["status"] || attrs[:deploy_response]
      @deploy_response = attrs["vm_id"] || attrs[:deploy_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "project_id" => @deploy_response,
        "status" => @deploy_response,
        "vm_id" => @deploy_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for GET /api/v1/repositories/{repo_name}/tags
  class ListRepoTagsResponse
    attr_accessor :list_repo_tags_response, :list_repo_tags_response, 

    def initialize(attrs = {})
      @list_repo_tags_response = attrs["repository"] || attrs[:list_repo_tags_response]
      @list_repo_tags_response = attrs["tags"] || attrs[:list_repo_tags_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "repository" => @list_repo_tags_response,
        "tags" => @list_repo_tags_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class BaseImageInfo
    attr_accessor :base_image_info, :base_image_info, :base_image_info, :base_image_info, :base_image_info, :base_image_info, :base_image_info, :base_image_info, 

    def initialize(attrs = {})
      @base_image_info = attrs["base_image_id"] || attrs[:base_image_info]
      @base_image_info = attrs["created_at"] || attrs[:base_image_info]
      @base_image_info = attrs["description"] || attrs[:base_image_info]
      @base_image_info = attrs["image_name"] || attrs[:base_image_info]
      @base_image_info = attrs["is_public"] || attrs[:base_image_info]
      @base_image_info = attrs["owner_id"] || attrs[:base_image_info]
      @base_image_info = attrs["size_mib"] || attrs[:base_image_info]
      @base_image_info = attrs["source_type"] || attrs[:base_image_info]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "base_image_id" => @base_image_info,
        "created_at" => @base_image_info,
        "description" => @base_image_info,
        "image_name" => @base_image_info,
        "is_public" => @base_image_info,
        "owner_id" => @base_image_info,
        "size_mib" => @base_image_info,
        "source_type" => @base_image_info,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for POST /api/vm/{vm_id}/exec
  class VmExecResponse
    attr_accessor :vm_exec_response, :vm_exec_response, :vm_exec_response, :vm_exec_response, 

    def initialize(attrs = {})
      @vm_exec_response = attrs["exec_id"] || attrs[:vm_exec_response]
      @vm_exec_response = attrs["exit_code"] || attrs[:vm_exec_response]
      @vm_exec_response = attrs["stderr"] || attrs[:vm_exec_response]
      @vm_exec_response = attrs["stdout"] || attrs[:vm_exec_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "exec_id" => @vm_exec_response,
        "exit_code" => @vm_exec_response,
        "stderr" => @vm_exec_response,
        "stdout" => @vm_exec_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class CreateBaseImageResponse
    attr_accessor :create_base_image_response, :create_base_image_response, :create_base_image_response, 

    def initialize(attrs = {})
      @create_base_image_response = attrs["image_name"] || attrs[:create_base_image_response]
      @create_base_image_response = attrs["job_id"] || attrs[:create_base_image_response]
      @create_base_image_response = attrs["status"] || attrs[:create_base_image_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "image_name" => @create_base_image_response,
        "job_id" => @create_base_image_response,
        "status" => @create_base_image_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for POST /api/vm/{vm_id}/exec
  class VmExecRequest
    attr_accessor :vm_exec_request, :vm_exec_request, :vm_exec_request, :vm_exec_request, :vm_exec_request, :vm_exec_request, 

    def initialize(attrs = {})
      @vm_exec_request = attrs["command"] || attrs[:vm_exec_request]
      @vm_exec_request = attrs["env"] || attrs[:vm_exec_request]
      @vm_exec_request = attrs["exec_id"] || attrs[:vm_exec_request]
      @vm_exec_request = attrs["stdin"] || attrs[:vm_exec_request]
      @vm_exec_request = attrs["timeout_secs"] || attrs[:vm_exec_request]
      @vm_exec_request = attrs["working_dir"] || attrs[:vm_exec_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "command" => @vm_exec_request,
        "env" => @vm_exec_request,
        "exec_id" => @vm_exec_request,
        "stdin" => @vm_exec_request,
        "timeout_secs" => @vm_exec_request,
        "working_dir" => @vm_exec_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class NewVmsResponse
    attr_accessor :new_vms_response, 

    def initialize(attrs = {})
      @new_vms_response = attrs["vms"] || attrs[:new_vms_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "vms" => @new_vms_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for POST /api/vm/{vm_id}/exec/stream/attach
  class VmExecStreamAttachRequest
    attr_accessor :vm_exec_stream_attach_request, :vm_exec_stream_attach_request, :vm_exec_stream_attach_request, 

    def initialize(attrs = {})
      @vm_exec_stream_attach_request = attrs["cursor"] || attrs[:vm_exec_stream_attach_request]
      @vm_exec_stream_attach_request = attrs["exec_id"] || attrs[:vm_exec_stream_attach_request]
      @vm_exec_stream_attach_request = attrs["from_latest"] || attrs[:vm_exec_stream_attach_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "cursor" => @vm_exec_stream_attach_request,
        "exec_id" => @vm_exec_stream_attach_request,
        "from_latest" => @vm_exec_stream_attach_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PATCH /api/vm/{vm_id}/state
  class VmUpdateStateRequest
    attr_accessor :vm_update_state_request, 

    def initialize(attrs = {})
      @vm_update_state_request = attrs["state"] || attrs[:vm_update_state_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "state" => @vm_update_state_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class DeleteBaseImageResponse
    attr_accessor :delete_base_image_response, :delete_base_image_response, 

    def initialize(attrs = {})
      @delete_base_image_response = attrs["base_image_id"] || attrs[:delete_base_image_response]
      @delete_base_image_response = attrs["deleted"] || attrs[:delete_base_image_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "base_image_id" => @delete_base_image_response,
        "deleted" => @delete_base_image_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for GET /api/v1/public/repositories
  class ListPublicRepositoriesResponse
    attr_accessor :list_public_repositories_response, 

    def initialize(attrs = {})
      @list_public_repositories_response = attrs["repositories"] || attrs[:list_public_repositories_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "repositories" => @list_public_repositories_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for POST /api/v1/commit_tags
  class CreateTagRequest
    attr_accessor :create_tag_request, :create_tag_request, :create_tag_request, 

    def initialize(attrs = {})
      @create_tag_request = attrs["commit_id"] || attrs[:create_tag_request]
      @create_tag_request = attrs["description"] || attrs[:create_tag_request]
      @create_tag_request = attrs["tag_name"] || attrs[:create_tag_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @create_tag_request,
        "description" => @create_tag_request,
        "tag_name" => @create_tag_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for GET /api/v1/repositories
  class ListRepositoriesResponse
    attr_accessor :list_repositories_response, 

    def initialize(attrs = {})
      @list_repositories_response = attrs["repositories"] || attrs[:list_repositories_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "repositories" => @list_repositories_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for POST /api/v1/repositories/{repo_name}/tags
  class CreateRepoTagResponse
    attr_accessor :create_repo_tag_response, :create_repo_tag_response, :create_repo_tag_response, 

    def initialize(attrs = {})
      @create_repo_tag_response = attrs["commit_id"] || attrs[:create_repo_tag_response]
      @create_repo_tag_response = attrs["reference"] || attrs[:create_repo_tag_response]
      @create_repo_tag_response = attrs["tag_id"] || attrs[:create_repo_tag_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @create_repo_tag_response,
        "reference" => @create_repo_tag_response,
        "tag_id" => @create_repo_tag_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class CommitInfo
    attr_accessor :commit_info, :commit_info, :commit_info, :commit_info, :commit_info, :commit_info, :commit_info, :commit_info, 

    def initialize(attrs = {})
      @commit_info = attrs["commit_id"] || attrs[:commit_info]
      @commit_info = attrs["created_at"] || attrs[:commit_info]
      @commit_info = attrs["description"] || attrs[:commit_info]
      @commit_info = attrs["grandparent_commit_id"] || attrs[:commit_info]
      @commit_info = attrs["is_public"] || attrs[:commit_info]
      @commit_info = attrs["name"] || attrs[:commit_info]
      @commit_info = attrs["owner_id"] || attrs[:commit_info]
      @commit_info = attrs["parent_vm_id"] || attrs[:commit_info]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @commit_info,
        "created_at" => @commit_info,
        "description" => @commit_info,
        "grandparent_commit_id" => @commit_info,
        "is_public" => @commit_info,
        "name" => @commit_info,
        "owner_id" => @commit_info,
        "parent_vm_id" => @commit_info,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for DELETE /api/v1/domains/{domain_id}
  class DeleteDomainResponse
    attr_accessor :delete_domain_response, 

    def initialize(attrs = {})
      @delete_domain_response = attrs["domain_id"] || attrs[:delete_domain_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "domain_id" => @delete_domain_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Repository information returned in list and get operations
  class RepositoryInfo
    attr_accessor :repository_info, :repository_info, :repository_info, :repository_info, :repository_info, 

    def initialize(attrs = {})
      @repository_info = attrs["created_at"] || attrs[:repository_info]
      @repository_info = attrs["description"] || attrs[:repository_info]
      @repository_info = attrs["is_public"] || attrs[:repository_info]
      @repository_info = attrs["name"] || attrs[:repository_info]
      @repository_info = attrs["repo_id"] || attrs[:repository_info]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "created_at" => @repository_info,
        "description" => @repository_info,
        "is_public" => @repository_info,
        "name" => @repository_info,
        "repo_id" => @repository_info,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for POST /api/keys/validate
  class ValidateKeyResponse
    attr_accessor :validate_key_response, :validate_key_response, 

    def initialize(attrs = {})
      @validate_key_response = attrs["message"] || attrs[:validate_key_response]
      @validate_key_response = attrs["valid"] || attrs[:validate_key_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "message" => @validate_key_response,
        "valid" => @validate_key_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for GET /api/vm/{vm_id}/ssh_key
  class VmSshKeyResponse
    attr_accessor :vm_ssh_key_response, :vm_ssh_key_response, 

    def initialize(attrs = {})
      @vm_ssh_key_response = attrs["ssh_port"] || attrs[:vm_ssh_key_response]
      @vm_ssh_key_response = attrs["ssh_private_key"] || attrs[:vm_ssh_key_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "ssh_port" => @vm_ssh_key_response,
        "ssh_private_key" => @vm_ssh_key_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # The state of a VM
  module VmState
    BOOTING = "booting"
    RUNNING = "running"
    PAUSED = "paused"
    SLEEPING = "sleeping"
    DEAD = "dead"

    ALL = [
      BOOTING,
      RUNNING,
      PAUSED,
      SLEEPING,
      DEAD
    ].freeze

    def self.values
      ALL
    end
  end

  # Response body for GET /api/vm/{vm_id}/files
  class VmReadFileResponse
    attr_accessor :vm_read_file_response, 

    def initialize(attrs = {})
      @vm_read_file_response = attrs["content_b64"] || attrs[:vm_read_file_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "content_b64" => @vm_read_file_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PUT /env_vars — sets (upserts) one or more environment variables.  # Lifecycle model  Environment variables are written to `/etc/environment` inside a VM **once at boot time** via a vsock `WriteFile` request. They are **not** live-synced to running VMs. This is intentional: VMs are ephemeral (create → use → destroy/branch), so env var changes naturally take effect on the next VM.  The `replace` flag exists so callers can atomically express 'I want exactly these variables and nothing else' without having to DELETE each stale key individually. Without it, the only way to remove a variable from future VMs is a separate `DELETE /env_vars/{key}` call per key.
  class SetEnvVarsRequest
    attr_accessor :set_env_vars_request, :set_env_vars_request, 

    def initialize(attrs = {})
      @set_env_vars_request = attrs["replace"] || attrs[:set_env_vars_request]
      @set_env_vars_request = attrs["vars"] || attrs[:set_env_vars_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "replace" => @set_env_vars_request,
        "vars" => @set_env_vars_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # The response body for POST /api/vm/{vm_id}/commit
  class VmCommitResponse
    attr_accessor :vm_commit_response, 

    def initialize(attrs = {})
      @vm_commit_response = attrs["commit_id"] || attrs[:vm_commit_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @vm_commit_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for POST /api/v1/repositories/fork
  class ForkRepositoryResponse
    attr_accessor :fork_repository_response, :fork_repository_response, :fork_repository_response, :fork_repository_response, :fork_repository_response, 

    def initialize(attrs = {})
      @fork_repository_response = attrs["commit_id"] || attrs[:fork_repository_response]
      @fork_repository_response = attrs["reference"] || attrs[:fork_repository_response]
      @fork_repository_response = attrs["repo_name"] || attrs[:fork_repository_response]
      @fork_repository_response = attrs["tag_name"] || attrs[:fork_repository_response]
      @fork_repository_response = attrs["vm_id"] || attrs[:fork_repository_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @fork_repository_response,
        "reference" => @fork_repository_response,
        "repo_name" => @fork_repository_response,
        "tag_name" => @fork_repository_response,
        "vm_id" => @fork_repository_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  module ImageSourceRequest
    class ImageRefVariant
      attr_accessor :data

      def initialize(data = {})
        @data = data
      end

      def self.from_json(obj)
        new(obj)
      end

      def to_h
        @data
      end
    end

    class BucketVariant
      attr_accessor :data

      def initialize(data = {})
        @data = data
      end

      def self.from_json(obj)
        new(obj)
      end

      def to_h
        @data
      end
    end

    VARIANT_CLASSES = [ImageRefVariant, BucketVariant].freeze

    def self.from_json(obj)
      return nil unless obj.is_a?(Hash)
      return ImageRefVariant.from_json(obj) if obj.key?("image_ref")
      return BucketVariant.from_json(obj) if obj.key?("bucket")
      nil
    end
  end

  # Possible options for the state requested in PATCH /api/vm/{vm_id}/state
  module VmUpdateStateEnum
    PAUSED = "Paused"
    RUNNING = "Running"

    ALL = [
      PAUSED,
      RUNNING
    ].freeze

    def self.values
      ALL
    end
  end

  # 
  class ErrorResponse
    attr_accessor :error_response, :error_response, 

    def initialize(attrs = {})
      @error_response = attrs["error"] || attrs[:error_response]
      @error_response = attrs["success"] || attrs[:error_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "error" => @error_response,
        "success" => @error_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PATCH /commits/{commit_id}
  class UpdateCommitRequest
    attr_accessor :update_commit_request, :update_commit_request, :update_commit_request, 

    def initialize(attrs = {})
      @update_commit_request = attrs["description"] || attrs[:update_commit_request]
      @update_commit_request = attrs["is_public"] || attrs[:update_commit_request]
      @update_commit_request = attrs["name"] || attrs[:update_commit_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "description" => @update_commit_request,
        "is_public" => @update_commit_request,
        "name" => @update_commit_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for POST /api/v1/repositories
  class CreateRepositoryRequest
    attr_accessor :create_repository_request, :create_repository_request, 

    def initialize(attrs = {})
      @create_repository_request = attrs["description"] || attrs[:create_repository_request]
      @create_repository_request = attrs["name"] || attrs[:create_repository_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "description" => @create_repository_request,
        "name" => @create_repository_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response type for domain operations.
  class DomainResponse
    attr_accessor :domain_response, :domain_response, :domain_response, :domain_response, 

    def initialize(attrs = {})
      @domain_response = attrs["created_at"] || attrs[:domain_response]
      @domain_response = attrs["domain"] || attrs[:domain_response]
      @domain_response = attrs["domain_id"] || attrs[:domain_response]
      @domain_response = attrs["vm_id"] || attrs[:domain_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "created_at" => @domain_response,
        "domain" => @domain_response,
        "domain_id" => @domain_response,
        "vm_id" => @domain_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # The request body for POST /api/vm/{vm_id}/commit
  class VmCommitRequest
    attr_accessor :vm_commit_request, :vm_commit_request, :vm_commit_request, 

    def initialize(attrs = {})
      @vm_commit_request = attrs["commit_id"] || attrs[:vm_commit_request]
      @vm_commit_request = attrs["description"] || attrs[:vm_commit_request]
      @vm_commit_request = attrs["name"] || attrs[:vm_commit_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @vm_commit_request,
        "description" => @vm_commit_request,
        "name" => @vm_commit_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Settings for the deploy build pipeline.
  class DeploySettings
    attr_accessor :deploy_settings, :deploy_settings, :deploy_settings, :deploy_settings, 

    def initialize(attrs = {})
      @deploy_settings = attrs["build_command"] || attrs[:deploy_settings]
      @deploy_settings = attrs["install_command"] || attrs[:deploy_settings]
      @deploy_settings = attrs["run_command"] || attrs[:deploy_settings]
      @deploy_settings = attrs["working_directory"] || attrs[:deploy_settings]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "build_command" => @deploy_settings,
        "install_command" => @deploy_settings,
        "run_command" => @deploy_settings,
        "working_directory" => @deploy_settings,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class CreateBaseImageRequest
    attr_accessor :create_base_image_request, :create_base_image_request, :create_base_image_request, :create_base_image_request, 

    def initialize(attrs = {})
      @create_base_image_request = attrs["description"] || attrs[:create_base_image_request]
      @create_base_image_request = attrs["image_name"] || attrs[:create_base_image_request]
      @create_base_image_request = attrs["size_mib"] || attrs[:create_base_image_request]
      @create_base_image_request = attrs["source"] || attrs[:create_base_image_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "description" => @create_base_image_request,
        "image_name" => @create_base_image_request,
        "size_mib" => @create_base_image_request,
        "source" => @create_base_image_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for POST /api/v1/repositories/fork
  class ForkRepositoryRequest
    attr_accessor :fork_repository_request, :fork_repository_request, :fork_repository_request, :fork_repository_request, :fork_repository_request, 

    def initialize(attrs = {})
      @fork_repository_request = attrs["repo_name"] || attrs[:fork_repository_request]
      @fork_repository_request = attrs["source_org"] || attrs[:fork_repository_request]
      @fork_repository_request = attrs["source_repo"] || attrs[:fork_repository_request]
      @fork_repository_request = attrs["source_tag"] || attrs[:fork_repository_request]
      @fork_repository_request = attrs["tag_name"] || attrs[:fork_repository_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "repo_name" => @fork_repository_request,
        "source_org" => @fork_repository_request,
        "source_repo" => @fork_repository_request,
        "source_tag" => @fork_repository_request,
        "tag_name" => @fork_repository_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class VmCommitEntity
    attr_accessor :vm_commit_entity, :vm_commit_entity, :vm_commit_entity, :vm_commit_entity, :vm_commit_entity, :vm_commit_entity, :vm_commit_entity, :vm_commit_entity, 

    def initialize(attrs = {})
      @vm_commit_entity = attrs["created_at"] || attrs[:vm_commit_entity]
      @vm_commit_entity = attrs["description"] || attrs[:vm_commit_entity]
      @vm_commit_entity = attrs["grandparent_commit_id"] || attrs[:vm_commit_entity]
      @vm_commit_entity = attrs["id"] || attrs[:vm_commit_entity]
      @vm_commit_entity = attrs["is_public"] || attrs[:vm_commit_entity]
      @vm_commit_entity = attrs["name"] || attrs[:vm_commit_entity]
      @vm_commit_entity = attrs["owner_id"] || attrs[:vm_commit_entity]
      @vm_commit_entity = attrs["parent_vm_id"] || attrs[:vm_commit_entity]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "created_at" => @vm_commit_entity,
        "description" => @vm_commit_entity,
        "grandparent_commit_id" => @vm_commit_entity,
        "id" => @vm_commit_entity,
        "is_public" => @vm_commit_entity,
        "name" => @vm_commit_entity,
        "owner_id" => @vm_commit_entity,
        "parent_vm_id" => @vm_commit_entity,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Tag information returned in list and get operations
  class TagInfo
    attr_accessor :tag_info, :tag_info, :tag_info, :tag_info, :tag_info, :tag_info, 

    def initialize(attrs = {})
      @tag_info = attrs["commit_id"] || attrs[:tag_info]
      @tag_info = attrs["created_at"] || attrs[:tag_info]
      @tag_info = attrs["description"] || attrs[:tag_info]
      @tag_info = attrs["tag_id"] || attrs[:tag_info]
      @tag_info = attrs["tag_name"] || attrs[:tag_info]
      @tag_info = attrs["updated_at"] || attrs[:tag_info]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @tag_info,
        "created_at" => @tag_info,
        "description" => @tag_info,
        "tag_id" => @tag_info,
        "tag_name" => @tag_info,
        "updated_at" => @tag_info,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PUT /api/vm/{vm_id}/files
  class VmWriteFileRequest
    attr_accessor :vm_write_file_request, :vm_write_file_request, :vm_write_file_request, :vm_write_file_request, 

    def initialize(attrs = {})
      @vm_write_file_request = attrs["content_b64"] || attrs[:vm_write_file_request]
      @vm_write_file_request = attrs["create_dirs"] || attrs[:vm_write_file_request]
      @vm_write_file_request = attrs["mode"] || attrs[:vm_write_file_request]
      @vm_write_file_request = attrs["path"] || attrs[:vm_write_file_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "content_b64" => @vm_write_file_request,
        "create_dirs" => @vm_write_file_request,
        "mode" => @vm_write_file_request,
        "path" => @vm_write_file_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Streams available for exec logging.
  module VmExecLogStream
    STDOUT = "stdout"
    STDERR = "stderr"

    ALL = [
      STDOUT,
      STDERR
    ].freeze

    def self.values
      ALL
    end
  end

  # Individual log entry describing emitted stdout/stderr chunk.
  class VmExecLogEntry
    attr_accessor :vm_exec_log_entry, :vm_exec_log_entry, :vm_exec_log_entry, :vm_exec_log_entry, 

    def initialize(attrs = {})
      @vm_exec_log_entry = attrs["data_b64"] || attrs[:vm_exec_log_entry]
      @vm_exec_log_entry = attrs["exec_id"] || attrs[:vm_exec_log_entry]
      @vm_exec_log_entry = attrs["stream"] || attrs[:vm_exec_log_entry]
      @vm_exec_log_entry = attrs["timestamp"] || attrs[:vm_exec_log_entry]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "data_b64" => @vm_exec_log_entry,
        "exec_id" => @vm_exec_log_entry,
        "stream" => @vm_exec_log_entry,
        "timestamp" => @vm_exec_log_entry,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class LabelVmRequest
    attr_accessor :label_vm_request, 

    def initialize(attrs = {})
      @label_vm_request = attrs["labels"] || attrs[:label_vm_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "labels" => @label_vm_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response for GET /api/v1/vm/{vm_id}/metadata
  class VmMetadataResponse
    attr_accessor :vm_metadata_response, :vm_metadata_response, :vm_metadata_response, :vm_metadata_response, :vm_metadata_response, :vm_metadata_response, :vm_metadata_response, :vm_metadata_response, 

    def initialize(attrs = {})
      @vm_metadata_response = attrs["created_at"] || attrs[:vm_metadata_response]
      @vm_metadata_response = attrs["deleted_at"] || attrs[:vm_metadata_response]
      @vm_metadata_response = attrs["grandparent_vm_id"] || attrs[:vm_metadata_response]
      @vm_metadata_response = attrs["ip"] || attrs[:vm_metadata_response]
      @vm_metadata_response = attrs["owner_id"] || attrs[:vm_metadata_response]
      @vm_metadata_response = attrs["parent_commit_id"] || attrs[:vm_metadata_response]
      @vm_metadata_response = attrs["state"] || attrs[:vm_metadata_response]
      @vm_metadata_response = attrs["vm_id"] || attrs[:vm_metadata_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "created_at" => @vm_metadata_response,
        "deleted_at" => @vm_metadata_response,
        "grandparent_vm_id" => @vm_metadata_response,
        "ip" => @vm_metadata_response,
        "owner_id" => @vm_metadata_response,
        "parent_commit_id" => @vm_metadata_response,
        "state" => @vm_metadata_response,
        "vm_id" => @vm_metadata_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PATCH /api/v1/repositories/{repo_name}/visibility
  class SetRepositoryVisibilityRequest
    attr_accessor :set_repository_visibility_request, 

    def initialize(attrs = {})
      @set_repository_visibility_request = attrs["is_public"] || attrs[:set_repository_visibility_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "is_public" => @set_repository_visibility_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PATCH /api/v1/repositories/{repo_name}/tags/{tag_name}
  class UpdateRepoTagRequest
    attr_accessor :update_repo_tag_request, :update_repo_tag_request, 

    def initialize(attrs = {})
      @update_repo_tag_request = attrs["commit_id"] || attrs[:update_repo_tag_request]
      @update_repo_tag_request = attrs["description"] || attrs[:update_repo_tag_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @update_repo_tag_request,
        "description" => @update_repo_tag_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Struct representing configuration options common to all VMs
  class VmCreateVmConfig
    attr_accessor :vm_create_vm_config, :vm_create_vm_config, :vm_create_vm_config, :vm_create_vm_config, :vm_create_vm_config, :vm_create_vm_config, 

    def initialize(attrs = {})
      @vm_create_vm_config = attrs["fs_size_mib"] || attrs[:vm_create_vm_config]
      @vm_create_vm_config = attrs["image_name"] || attrs[:vm_create_vm_config]
      @vm_create_vm_config = attrs["kernel_name"] || attrs[:vm_create_vm_config]
      @vm_create_vm_config = attrs["labels"] || attrs[:vm_create_vm_config]
      @vm_create_vm_config = attrs["mem_size_mib"] || attrs[:vm_create_vm_config]
      @vm_create_vm_config = attrs["vcpu_count"] || attrs[:vm_create_vm_config]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "fs_size_mib" => @vm_create_vm_config,
        "image_name" => @vm_create_vm_config,
        "kernel_name" => @vm_create_vm_config,
        "labels" => @vm_create_vm_config,
        "mem_size_mib" => @vm_create_vm_config,
        "vcpu_count" => @vm_create_vm_config,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for new VM requests (new_root, from_commit, branch)
  class NewVmResponse
    attr_accessor :new_vm_response, 

    def initialize(attrs = {})
      @new_vm_response = attrs["vm_id"] || attrs[:new_vm_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "vm_id" => @new_vm_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for POST /api/v1/vm/from_commit
  module FromCommitVmRequest
    class CommitIdVariant
      attr_accessor :data

      def initialize(data = {})
        @data = data
      end

      def self.from_json(obj)
        new(obj)
      end

      def to_h
        @data
      end
    end

    class TagNameVariant
      attr_accessor :data

      def initialize(data = {})
        @data = data
      end

      def self.from_json(obj)
        new(obj)
      end

      def to_h
        @data
      end
    end

    class RefVariant
      attr_accessor :data

      def initialize(data = {})
        @data = data
      end

      def self.from_json(obj)
        new(obj)
      end

      def to_h
        @data
      end
    end

    VARIANT_CLASSES = [CommitIdVariant, TagNameVariant, RefVariant].freeze

    def self.from_json(obj)
      return nil unless obj.is_a?(Hash)
      return CommitIdVariant.from_json(obj) if obj.key?("commit_id")
      return TagNameVariant.from_json(obj) if obj.key?("tag_name")
      return RefVariant.from_json(obj) if obj.key?("ref")
      nil
    end
  end

  # 
  class VM
    attr_accessor :v_m, :v_m, :v_m, :v_m, :v_m, 

    def initialize(attrs = {})
      @v_m = attrs["created_at"] || attrs[:v_m]
      @v_m = attrs["labels"] || attrs[:v_m]
      @v_m = attrs["owner_id"] || attrs[:v_m]
      @v_m = attrs["state"] || attrs[:v_m]
      @v_m = attrs["vm_id"] || attrs[:v_m]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "created_at" => @v_m,
        "labels" => @v_m,
        "owner_id" => @v_m,
        "state" => @v_m,
        "vm_id" => @v_m,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for POST /api/v1/domains
  class CreateDomainRequest
    attr_accessor :create_domain_request, :create_domain_request, 

    def initialize(attrs = {})
      @create_domain_request = attrs["domain"] || attrs[:create_domain_request]
      @create_domain_request = attrs["vm_id"] || attrs[:create_domain_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "domain" => @create_domain_request,
        "vm_id" => @create_domain_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PATCH /api/v1/commit_tags/{tag_name}  For `description`: - Field absent from JSON → don't change the description - Field present as `null` → clear the description - Field present as `'text'` → set the description to 'text'
  class UpdateTagRequest
    attr_accessor :update_tag_request, :update_tag_request, 

    def initialize(attrs = {})
      @update_tag_request = attrs["commit_id"] || attrs[:update_tag_request]
      @update_tag_request = attrs["description"] || attrs[:update_tag_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @update_tag_request,
        "description" => @update_tag_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class UploadBaseImageResponse
    attr_accessor :upload_base_image_response, :upload_base_image_response, :upload_base_image_response, 

    def initialize(attrs = {})
      @upload_base_image_response = attrs["image_name"] || attrs[:upload_base_image_response]
      @upload_base_image_response = attrs["job_id"] || attrs[:upload_base_image_response]
      @upload_base_image_response = attrs["status"] || attrs[:upload_base_image_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "image_name" => @upload_base_image_response,
        "job_id" => @upload_base_image_response,
        "status" => @upload_base_image_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class BaseImageStatusResponse
    attr_accessor :base_image_status_response, :base_image_status_response, :base_image_status_response, :base_image_status_response, 

    def initialize(attrs = {})
      @base_image_status_response = attrs["error_message"] || attrs[:base_image_status_response]
      @base_image_status_response = attrs["image_name"] || attrs[:base_image_status_response]
      @base_image_status_response = attrs["size_mib"] || attrs[:base_image_status_response]
      @base_image_status_response = attrs["status"] || attrs[:base_image_status_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "error_message" => @base_image_status_response,
        "image_name" => @base_image_status_response,
        "size_mib" => @base_image_status_response,
        "status" => @base_image_status_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class ListBaseImagesResponse
    attr_accessor :list_base_images_response, :list_base_images_response, :list_base_images_response, :list_base_images_response, 

    def initialize(attrs = {})
      @list_base_images_response = attrs["images"] || attrs[:list_base_images_response]
      @list_base_images_response = attrs["limit"] || attrs[:list_base_images_response]
      @list_base_images_response = attrs["offset"] || attrs[:list_base_images_response]
      @list_base_images_response = attrs["total"] || attrs[:list_base_images_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "images" => @list_base_images_response,
        "limit" => @list_base_images_response,
        "offset" => @list_base_images_response,
        "total" => @list_base_images_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # 
  class NewRootRequest
    attr_accessor :new_root_request, 

    def initialize(attrs = {})
      @new_root_request = attrs["vm_config"] || attrs[:new_root_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "vm_config" => @new_root_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for PATCH /api/vm/{vm_id}/disk
  class VmResizeDiskRequest
    attr_accessor :vm_resize_disk_request, 

    def initialize(attrs = {})
      @vm_resize_disk_request = attrs["fs_size_mib"] || attrs[:vm_resize_disk_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "fs_size_mib" => @vm_resize_disk_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for DELETE /api/vm/{vm_id}
  class VmDeleteResponse
    attr_accessor :vm_delete_response, 

    def initialize(attrs = {})
      @vm_delete_response = attrs["vm_id"] || attrs[:vm_delete_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "vm_id" => @vm_delete_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response body for POST /api/v1/commit_tags
  class CreateTagResponse
    attr_accessor :create_tag_response, :create_tag_response, :create_tag_response, 

    def initialize(attrs = {})
      @create_tag_response = attrs["commit_id"] || attrs[:create_tag_response]
      @create_tag_response = attrs["tag_id"] || attrs[:create_tag_response]
      @create_tag_response = attrs["tag_name"] || attrs[:create_tag_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @create_tag_response,
        "tag_id" => @create_tag_response,
        "tag_name" => @create_tag_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Request body for `POST /api/v1/deploy`.
  class DeployRequest
    attr_accessor :deploy_request, :deploy_request, :deploy_request, :deploy_request, 

    def initialize(attrs = {})
      @deploy_request = attrs["branch"] || attrs[:deploy_request]
      @deploy_request = attrs["name"] || attrs[:deploy_request]
      @deploy_request = attrs["repo"] || attrs[:deploy_request]
      @deploy_request = attrs["settings"] || attrs[:deploy_request]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "branch" => @deploy_request,
        "name" => @deploy_request,
        "repo" => @deploy_request,
        "settings" => @deploy_request,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Tag information within a repository context
  class RepoTagInfo
    attr_accessor :repo_tag_info, :repo_tag_info, :repo_tag_info, :repo_tag_info, :repo_tag_info, :repo_tag_info, :repo_tag_info, 

    def initialize(attrs = {})
      @repo_tag_info = attrs["commit_id"] || attrs[:repo_tag_info]
      @repo_tag_info = attrs["created_at"] || attrs[:repo_tag_info]
      @repo_tag_info = attrs["description"] || attrs[:repo_tag_info]
      @repo_tag_info = attrs["reference"] || attrs[:repo_tag_info]
      @repo_tag_info = attrs["tag_id"] || attrs[:repo_tag_info]
      @repo_tag_info = attrs["tag_name"] || attrs[:repo_tag_info]
      @repo_tag_info = attrs["updated_at"] || attrs[:repo_tag_info]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "commit_id" => @repo_tag_info,
        "created_at" => @repo_tag_info,
        "description" => @repo_tag_info,
        "reference" => @repo_tag_info,
        "tag_id" => @repo_tag_info,
        "tag_name" => @repo_tag_info,
        "updated_at" => @repo_tag_info,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end

  # Response for exec log tail requests.
  class VmExecLogResponse
    attr_accessor :vm_exec_log_response, :vm_exec_log_response, :vm_exec_log_response, 

    def initialize(attrs = {})
      @vm_exec_log_response = attrs["entries"] || attrs[:vm_exec_log_response]
      @vm_exec_log_response = attrs["eof"] || attrs[:vm_exec_log_response]
      @vm_exec_log_response = attrs["next_offset"] || attrs[:vm_exec_log_response]
    end

    def self.from_json(json_str)
      obj = json_str.is_a?(String) ? JSON.parse(json_str) : json_str
      new(obj)
    end

    def to_h
      {
        "entries" => @vm_exec_log_response,
        "eof" => @vm_exec_log_response,
        "next_offset" => @vm_exec_log_response,
      }
    end

    def to_json(*args)
      to_h.to_json(*args)
    end

  end


  # ── Params types for operations with query parameters ───────────────

  # Query parameters for ResizeVmDiskParams
  class ResizeVmDiskParams
    attr_accessor :skip_wait_boot, 

    def initialize(attrs = {})
      @skip_wait_boot = attrs[:skip_wait_boot] || attrs["skip_wait_boot"]
    end

    def to_h
      h = {}
      h["skip_wait_boot"] = @skip_wait_boot unless @skip_wait_boot.nil?
      h
    end
  end

  # Query parameters for CreateNewRootVmParams
  class CreateNewRootVmParams
    attr_accessor :wait_boot, 

    def initialize(attrs = {})
      @wait_boot = attrs[:wait_boot] || attrs["wait_boot"]
    end

    def to_h
      h = {}
      h["wait_boot"] = @wait_boot unless @wait_boot.nil?
      h
    end
  end

  # Query parameters for VmLogsParams
  class VmLogsParams
    attr_accessor :offset, :max_entries, :stream, 

    def initialize(attrs = {})
      @offset = attrs[:offset] || attrs["offset"]
      @max_entries = attrs[:max_entries] || attrs["max_entries"]
      @stream = attrs[:stream] || attrs["stream"]
    end

    def to_h
      h = {}
      h["offset"] = @offset unless @offset.nil?
      h["max_entries"] = @max_entries unless @max_entries.nil?
      h["stream"] = @stream unless @stream.nil?
      h
    end
  end

  # Query parameters for BranchByRefParams
  class BranchByRefParams
    attr_accessor :count, 

    def initialize(attrs = {})
      @count = attrs[:count] || attrs["count"]
    end

    def to_h
      h = {}
      h["count"] = @count unless @count.nil?
      h
    end
  end

  # Query parameters for BranchByTagParams
  class BranchByTagParams
    attr_accessor :count, 

    def initialize(attrs = {})
      @count = attrs[:count] || attrs["count"]
    end

    def to_h
      h = {}
      h["count"] = @count unless @count.nil?
      h
    end
  end

  # Query parameters for BranchVmParams
  class BranchVmParams
    attr_accessor :keep_paused, :skip_wait_boot, :count, 

    def initialize(attrs = {})
      @keep_paused = attrs[:keep_paused] || attrs["keep_paused"]
      @skip_wait_boot = attrs[:skip_wait_boot] || attrs["skip_wait_boot"]
      @count = attrs[:count] || attrs["count"]
    end

    def to_h
      h = {}
      h["keep_paused"] = @keep_paused unless @keep_paused.nil?
      h["skip_wait_boot"] = @skip_wait_boot unless @skip_wait_boot.nil?
      h["count"] = @count unless @count.nil?
      h
    end
  end

  # Query parameters for UpdateVmStateParams
  class UpdateVmStateParams
    attr_accessor :skip_wait_boot, 

    def initialize(attrs = {})
      @skip_wait_boot = attrs[:skip_wait_boot] || attrs["skip_wait_boot"]
    end

    def to_h
      h = {}
      h["skip_wait_boot"] = @skip_wait_boot unless @skip_wait_boot.nil?
      h
    end
  end

  # Query parameters for DeleteVmParams
  class DeleteVmParams
    attr_accessor :skip_wait_boot, 

    def initialize(attrs = {})
      @skip_wait_boot = attrs[:skip_wait_boot] || attrs["skip_wait_boot"]
    end

    def to_h
      h = {}
      h["skip_wait_boot"] = @skip_wait_boot unless @skip_wait_boot.nil?
      h
    end
  end

  # Query parameters for BranchByVmParams
  class BranchByVmParams
    attr_accessor :keep_paused, :skip_wait_boot, :count, 

    def initialize(attrs = {})
      @keep_paused = attrs[:keep_paused] || attrs["keep_paused"]
      @skip_wait_boot = attrs[:skip_wait_boot] || attrs["skip_wait_boot"]
      @count = attrs[:count] || attrs["count"]
    end

    def to_h
      h = {}
      h["keep_paused"] = @keep_paused unless @keep_paused.nil?
      h["skip_wait_boot"] = @skip_wait_boot unless @skip_wait_boot.nil?
      h["count"] = @count unless @count.nil?
      h
    end
  end

  # Query parameters for CommitVmParams
  class CommitVmParams
    attr_accessor :keep_paused, :skip_wait_boot, 

    def initialize(attrs = {})
      @keep_paused = attrs[:keep_paused] || attrs["keep_paused"]
      @skip_wait_boot = attrs[:skip_wait_boot] || attrs["skip_wait_boot"]
    end

    def to_h
      h = {}
      h["keep_paused"] = @keep_paused unless @keep_paused.nil?
      h["skip_wait_boot"] = @skip_wait_boot unless @skip_wait_boot.nil?
      h
    end
  end

  # Query parameters for ListDomainsParams
  class ListDomainsParams
    attr_accessor :vm_id, 

    def initialize(attrs = {})
      @vm_id = attrs[:vm_id] || attrs["vm_id"]
    end

    def to_h
      h = {}
      h["vm_id"] = @vm_id unless @vm_id.nil?
      h
    end
  end

  # Query parameters for ReadFileVmParams
  class ReadFileVmParams
    attr_accessor :path, 

    def initialize(attrs = {})
      @path = attrs[:path] || attrs["path"]
    end

    def to_h
      h = {}
      h["path"] = @path unless @path.nil?
      h
    end
  end

  # Query parameters for BranchByCommitParams
  class BranchByCommitParams
    attr_accessor :count, 

    def initialize(attrs = {})
      @count = attrs[:count] || attrs["count"]
    end

    def to_h
      h = {}
      h["count"] = @count unless @count.nil?
      h
    end
  end

end
