# frozen_string_literal: true

# Generated by Sterling SDK Generator
# Orchestrator Control Plane API v0.1.0

require_relative "vers_sdk/errors"
require_relative "vers_sdk/models"
require_relative "vers_sdk/client"

module VersSdk
  VERSION = "0.1.8"
end
